POST config to algo
---
tags:
- Puh config
parameters:
  - name: file
    in: body
    description: config algo dict
    required: true
    schema:
      $ref: '#/components/schemas/algo_config'

responses:
  200:
    schema:
      $ref: '#/components/schemas/algo_config'
  400:
    $ref: '#/components/responses/400BadRequest'
  403:
    $ref: '#/components/responses/403Forbidden'
  404:
    $ref: '#/components/responses/404NotFound'